# Generated by Django 6.0.3 on 2026-09-02 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('category', models.CharField(default='Enterprise RAG & AI', max_length=100)),
                ('priority', models.CharField(choices=[('standard', 'Standard Velocity'), ('high', 'High Priority'), ('urgent', 'Urgent / Blocker Resolution')], default='high', max_length=20)),
                ('sprint_status', models.CharField(choices=[('scoping', 'Architecture Scoping'), ('active_sprint', 'Active Development Sprint'), ('qa_testing', 'QA & Staging Review'), ('deployed', 'Production Deployed'), ('maintenance', '24/7 SLA Maintenance')], default='active_sprint', max_length=30)),
                ('sprint_progress', models.IntegerField(default=75)),
                ('staging_url', models.URLField(blank=True, default='https://staging.internal.nconix.com')),
                ('architecture_doc_url', models.CharField(blank=True, default='/docs/architecture-spec.pdf', max_length=255)),
                ('nda_signed', models.BooleanField(default=True)),
                ('budget_estimate', models.CharField(blank=True, default='$8,500', max_length=100)),
                ('timeline', models.CharField(blank=True, default='4-6 Weeks', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Project',
                'verbose_name_plural': 'Client Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('client', 'Client'), ('architect', 'Lead Architect'), ('admin', 'Admin')], default='client', max_length=20)),
                ('sender_name', models.CharField(default='Client Lead', max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='client_portal.clientproject')),
            ],
            options={
                'verbose_name': 'Client Chat Message',
                'verbose_name_plural': 'Client Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(default='Enterprise RAG & AI', max_length=100)),
                ('priority', models.CharField(default='high', max_length=20)),
                ('timeline', models.CharField(blank=True, default='4 Weeks', max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='submitted', max_length=30)),
                ('sprint_progress', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='client_portal.clientproject')),
            ],
            options={
                'verbose_name': 'Client Requirement',
                'verbose_name_plural': 'Client Requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
