# Generated by Django 6.0.3 on 2026-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(default='client', max_length=20)),
                ('sender_name', models.CharField(default='Client', max_length=150)),
                ('channel', models.CharField(default='client_admin_chat', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portal Message',
                'verbose_name_plural': 'Portal Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(default='Custom Software', max_length=100)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('high', 'High Priority'), ('urgent', 'Urgent / Critical')], default='standard', max_length=20)),
                ('description', models.TextField()),
                ('timeline', models.CharField(blank=True, default='4-6 weeks', max_length=100)),
                ('budget_estimate', models.CharField(blank=True, default='$5,000 - $10,000', max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Requirement Submitted'), ('scoping', 'Architecture Scoping'), ('in_development', 'In Active Sprint'), ('qa_testing', 'QA & Staging Review'), ('deployed', 'Production Deployed')], default='in_development', max_length=30)),
                ('sprint_progress', models.IntegerField(default=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Requirement',
                'verbose_name_plural': 'Project Requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
