# Generated by Django 6.0.3 on 2026-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=2418)),
                ('active_enterprise_clients', models.IntegerField(default=18)),
                ('monthly_arr', models.CharField(default='$148,000', max_length=50)),
                ('cluster_uptime', models.CharField(default='99.99%', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform Metrics Snapshot',
                'verbose_name_plural': 'Platform Metrics Snapshots',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Activity Log',
                'verbose_name_plural': 'System Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
