# Generated by Django 6.0.3 on 2026-09-02 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMentorChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('sender_type', models.CharField(choices=[('student', 'Student'), ('mentor', 'Academy Mentor')], default='student', max_length=20)),
                ('sender_name', models.CharField(default='Student', max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student-Mentor Message',
                'verbose_name_plural': 'Student-Mentor Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('course_title', models.CharField(default='Generative AI with Python & Autonomous Agents', max_length=200)),
                ('course_slug', models.SlugField(default='generative-ai-python', max_length=100)),
                ('progress_percentage', models.IntegerField(default=84)),
                ('current_module', models.CharField(default='Module 7: Multi-Agent Tool Calling with LangGraph', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active In Progress'), ('completed', 'Completed & Certified'), ('paused', 'Paused')], default='active', max_length=20)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_url', models.CharField(blank=True, max_length=255)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Course Enrollment',
                'verbose_name_plural': 'Student Course Enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('assignment_title', models.CharField(default='Capstone: Private RAG Vector Index Pipeline', max_length=200)),
                ('github_repo_url', models.URLField(max_length=300)),
                ('grade_score', models.IntegerField(default=100)),
                ('mentor_feedback', models.TextField(blank=True, default='Excellent AST implementation, clean docstrings, all 9 test suites passing.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted (Tests Pending)'), ('graded', 'Graded & Approved'), ('revision_needed', 'Revision Requested')], default='graded', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='student_portal.studentcourseenrollment')),
            ],
            options={
                'verbose_name': 'Student Assignment',
                'verbose_name_plural': 'Student Assignments',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
